{
	"openapi": "3.0.0",
	"info": {
		"title": "Giftcard Provider Protocol",
		"description": "The _Gift Card Provider Protocol_ is a set of definitions to help you integrate your gift card API into VTEX platform. To achieve this, you need to implement a web API (REST) following the specifications from this documentation and configure your provider in your store using _Gift Card Hub API_.\n\n##### MORE INFORMATION\n\n---\n\n\n> *VTEX Help Center - Gift Card Hub API*: \nhttps://documenter.getpostman.com/view/18468/RVfqmDgC\n\n\n##### COMMON PARAMETERS IN THE DOCUMENTATION\n\n---\n\n<table>\n  <tr>\n    <td><code>{{providerApiEndpoint}}</code></td>\n    <td>Provider's endpoint for the implementation (mandatory)</td>\n  </tr>\n  <tr>\n    <td><code>{{X-PROVIDER-API-AppKey}}</code></td>\n    <td>The AppKey configured by the merchant (optional)</td>\n  </tr>\n  <tr>\n    <td><code>{{X-PROVIDER-API-AppToken}}</code></td>\n    <td>The AppToken configured by the merchant (optional)</td>\n  </tr>\n</table>",
		"contact": {},
		"version": "1.0"
	},
	"servers": [
		{
			"url": "https://{providerApiEndpoint}/",
			"description": "VTEX server url"
		}
	],
	"paths": {
		"/api/giftcards/_search": {
			"post": {
				"tags": [
					"Gift Cards"
				],
				"summary": "List All GiftCards",
				"description": "Request a list of all giftcards available for a given client/cart(request).",
				"operationId": "ListAllGiftCards",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "REST-Range",
						"in": "header",
						"description": "Pagination control. This query variable must follow the format _resources={from}-{to}_.",
						"required": false,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "resources=0-49"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/vnd.vtex.giftcardproviders.v1+json": {
							"schema": {
								"$ref": "#/components/schemas/ListAllGiftCardsRequest"
							},
							"example": {
								"client": {
									"id": "3b1abc17",
									"email": "email@domain.com",
									"document": "234235"
								},
								"cart": {
									"grandTotal": 182,
									"relationName": null,
									"redemptionCode": "XTYB",
									"discounts": 20,
									"shipping": 2,
									"taxes": 0,
									"items": [
										{
											"productId": "2000",
											"id": "2002",
											"refId": "MEV41",
											"name": null,
											"price": 200,
											"quantity": 1
										}
									],
									"itemsTotal": 200
								}
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/response"
									}
								},
								"example": [
									{
										"id": "3ad63br54-988e-4a14-8b7f-31fc6a5b955c_24",
										"provider": "ProviderName",
										"balance": 5.9,
										"_self": {
											"href": "/gatewayqa/giftcards/3ad63br54-988e-4a14-8b7f-31fc6a5b955c_24"
										}
									}
								]
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/api/giftcards/{giftCardID}": {
			"get": {
				"tags": [
					"Gift Cards"
				],
				"summary": "Get GiftCard by ID",
				"description": "Returns a specific giftcard with details.",
				"operationId": "GetGiftCardbyID",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response1"
								},
								"example": {
									"id": "3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24",
									"redemptionToken": "XTYB-IOBW-WLJE-SEYG",
									"redemptionCode": "XTYB-IOBW-WLJE-SEYG",
									"balance": 5.9,
									"emissionDate": "2018-03-20T09:37:13.797",
									"expiringDate": "2020-03-18T11:42:55.183",
									"transaction": {
										"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions"
									}
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/api/giftcards": {
			"post": {
				"tags": [
					"Gift Cards"
				],
				"summary": "Create GiftCard",
				"description": "Creates a giftcard in a giftcard provider.",
				"operationId": "CreateGiftCard",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/vnd.vtex.giftcardproviders.v1+json": {
							"schema": {
								"$ref": "#/components/schemas/CreateGiftCardRequest"
							},
							"example": {
								"relationName": "loyalty-program",
								"emissionDate": "2011-02-04T17:02:19.17",
								"expiringDate": "2020-02-04T17:02:19.17",
								"caption": "Loyalty Program",
								"restrictedToOwner": true,
								"multipleRedemptions": true,
								"multipleCredits": true,
								"profileId": "92de2449-0e02-4ca9-a4aa-a09cc9d8f7ff"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"text/plain": {
								"schema": {
									"type": "object"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions": {
			"post": {
				"tags": [
					"Transactions"
				],
				"summary": "Create GiftCard Transaction",
				"description": "Creates a transaction to a giftcard.",
				"operationId": "CreateGiftCardTransaction",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert idetifier here"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/vnd.vtex.giftcardproviders.v1+json": {
							"schema": {
								"$ref": "#/components/schemas/CreateGiftCardTransactionRequest"
							},
							"example": {
								"operation": "Credit",
								"value": 28.4,
								"description": "Order v2915869org-01",
								"redemptionToken": "QFJA-AUKP-TXKU-GCKV",
								"redemptionCode": null,
								"requestId": "v2915869org-01",
								"orderInfo": {
									"orderId": "v2915869org-01",
									"sequence": 2915869,
									"cart": {
										"items": [
											{
												"id": "2000330",
												"productId": "2000196",
												"refId": null,
												"name": "T-Shirt M",
												"value": 15,
												"price": 15,
												"quantity": 1,
												"shippingDiscount": 0,
												"discount": 0,
												"priceTags": []
											}
										],
										"grandTotal": 0,
										"discounts": 0,
										"shipping": 0,
										"taxes": 0,
										"itemsTotal": 15
									},
									"clientProfile": {
										"email": "email@domain.com",
										"firstName": "John",
										"lastName": "Smith",
										"document": "10617764093",
										"documentType": "cpf",
										"phone": "+5521993759875",
										"birthDate": "0001-01-01T00:00:00",
										"isCorporate": false
									},
									"shipping": {
										"receiverName": "John Smith",
										"postalCode": "24417-246",
										"city": "Leblon",
										"state": "RJ",
										"country": "BRA",
										"street": "Rua Aidea Barreto do Couto",
										"number": "9678",
										"neighborhood": "",
										"complement": "",
										"reference": ""
									}
								}
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response2"
								},
								"example": {
									"cardId": "24",
									"id": "68347b311ce5407c90fa5316975d047a",
									"_self": {
										"href": "gatewayqa/giftcards/24/transactions/68347b311ce5407c90fa5316975d047a"
									}
								}
							}
						}
					}
				},
				"deprecated": false
			},
			"get": {
				"tags": [
					"Transactions"
				],
				"summary": "List All GiftCard Transactions",
				"description": "Return a summary of all transactions from a giftcard.",
				"operationId": "ListAllGiftCardTransactions",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/response2"
									}
								},
								"example": [
									{
										"cardId": "3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24",
										"id": "68347b311ce5407c90fa5316975d047a",
										"_self": {
											"href": "gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/68347b311ce5407c90fa5316975d047a"
										}
									},
									{
										"cardId": "3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24",
										"id": "e122ebd4501a4b3b93640b7444ac425d",
										"_self": {
											"href": "gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d"
										}
									}
								]
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}": {
			"get": {
				"tags": [
					"Transactions"
				],
				"summary": "Get GiftCard Transaction by ID",
				"description": "Returns a specific giftcard transaction.",
				"operationId": "GetGiftCardTransactionbyID",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/GetGiftCardTransactionbyID"
								},
								"example": {
									"value": 5.92,
									"description": "Order v2915869org-02",
									"date": "2019-03-18T14:42:32.1291783Z",
									"requestId": "v2915869org-02",
									"orderInfo": {
										"orderId": "v2915869org-02",
										"sequence": 2915860,
										"cart": {
											"items": [
												{
													"id": "2000330",
													"productId": "2000196",
													"name": "T-Shirt M",
													"price": 15,
													"sellingPrice": 0,
													"quantity": 1,
													"totalShippingDiscount": 0,
													"totalDiscount": 0,
													"priceTags": []
												}
											],
											"grandTotal": 0,
											"discounts": 0,
											"shipping": 0,
											"taxes": 0,
											"itemsTotal": 15
										},
										"clientProfile": {
											"email": "email@domain.com",
											"firstName": "John",
											"lastName": "Smith",
											"document": "10617764093",
											"documentType": "cpf",
											"phone": "+5521993759875",
											"birthDate": "0001-01-01T00:00:00",
											"isCorporate": false
										},
										"shipping": {
											"receiverName": "John Smith",
											"postalCode": "24417-246",
											"city": "Leblon",
											"state": "RJ",
											"country": "BRA",
											"street": "Rua Aidea Barreto do Couto",
											"number": "9678",
											"neighborhood": "",
											"complement": "",
											"reference": ""
										}
									},
									"settlement": {
										"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/settlements"
									},
									"cancellation": {
										"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/cancellations"
									},
									"authorization": {
										"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/authorization"
									},
									"operation": "Debit"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}/authorization": {
			"get": {
				"tags": [
					"Transactions"
				],
				"summary": "Get GiftCard Transaction Authorization",
				"description": "Returns the transaction authorization info.",
				"operationId": "GetGiftCardTransactionAuthorization",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response4"
								},
								"example": {
									"oid": "e122ebd4501a4b3b93640b7444ac425d",
									"value": 5.92,
									"date": "2019-03-18T14:42:32.1291783Z"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}/cancellations": {
			"post": {
				"tags": [
					"Transactions"
				],
				"summary": "Create GiftCard Transaction Cancellation",
				"description": "Creates a cancellation transaction to a giftcard.",
				"operationId": "CreateGiftCardTransactionCancellation",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/vnd.vtex.giftcardproviders.v1+json": {
							"schema": {
								"$ref": "#/components/schemas/CreateGiftCardTransactionCancellationRequest"
							},
							"example": {
								"value": 4.1,
								"requestId": "12093812masoidj120398"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response4"
								},
								"example": {
									"oid": "7582d93baccc44e9867b0b861696fc0a",
									"value": 4.1,
									"date": "2019-03-19T14:35:16.7157238Z"
								}
							}
						}
					}
				},
				"deprecated": false
			},
			"get": {
				"tags": [
					"Transactions"
				],
				"summary": "List All GiftCard Transactions Cancellations",
				"description": "Returns a collection of transaction cancellations from a giftcard.",
				"operationId": "ListAllGiftCardTransactionsCancellations",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/response4"
									}
								},
								"example": [
									{
										"oid": "7582d93baccc44e9867b0b861696fc0a",
										"value": 4.1,
										"date": "2019-03-19T14:35:16.7157238Z"
									}
								]
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}/settlements": {
			"post": {
				"tags": [
					"Transactions"
				],
				"summary": "Create GiftCard Transaction Settlement",
				"description": "Creates a settlement transaction to a giftcard.",
				"operationId": "CreateGiftCardTransactionSettlement",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/vnd.vtex.giftcardproviders.v1+json": {
							"schema": {
								"$ref": "#/components/schemas/CreateGiftCardTransactionSettlementRequest"
							},
							"example": {
								"value": 1.8,
								"requestId": "12093812masoidj120398"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"text/plain": {
								"schema": {
									"type": "object"
								}
							}
						}
					}
				},
				"deprecated": false
			},
			"get": {
				"tags": [
					"Transactions"
				],
				"summary": "List All GiftCard Transactions Settlements",
				"description": "Returns a collection of settlement transactions from a giftcard.",
				"operationId": "ListAllGiftCardTransactionsSettlements",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "application/json"
						}
					},
					{
						"name": "X-PROVIDER-API-AppKey",
						"in": "header",
						"description": "The AppKey configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppKey}}"
						}
					},
					{
						"name": "X-PROVIDER-API-AppToken",
						"in": "header",
						"description": "The AppToken configured by the merchant (optional configuration)",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "{{X-PROVIDER-API-AppToken}}"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"default": "insert identifier here"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"text/plain": {
								"schema": {
									"type": "object"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		}
	},
	"components": {
		"schemas": {
			"ListAllGiftCardsRequest": {
				"title": "ListAllGiftCardsRequest",
				"required": [
					"client",
					"cart"
				],
				"type": "object",
				"properties": {
					"client": {
						"$ref": "#/components/schemas/Client"
					},
					"cart": {
						"$ref": "#/components/schemas/Cart"
					}
				},
				"default": {
					"client": {
						"id": "3b1ab",
						"email": "email@domain.com",
						"document": "234235"
					},
					"cart": {
						"grandTotal": 182,
						"relationName": null,
						"redemptionCode": "XTYB",
						"discounts": 20,
						"shipping": 2,
						"taxes": 0,
						"items": [
							{
								"productId": "2000",
								"id": "20002",
								"refId": "MEV41",
								"name": null,
								"price": 200,
								"quantity": 1
							}
						],
						"itemsTotal": 200
					}
				}
			},
			"Client": {
				"title": "Client",
				"required": [
					"id",
					"email",
					"document"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"email": {
						"type": "string"
					},
					"document": {
						"type": "string"
					}
				},
				"default": {
					"id": "3b1abc17",
					"email": "email@domain.com",
					"document": "234235"
				}
			},
			"Cart": {
				"title": "Cart",
				"required": [
					"grandTotal",
					"relationName",
					"redemptionCode",
					"discounts",
					"shipping",
					"taxes",
					"items",
					"itemsTotal"
				],
				"type": "object",
				"properties": {
					"grandTotal": {
						"type": "integer",
						"format": "int32"
					},
					"relationName": {
						"type": "string",
						"nullable": true
					},
					"redemptionCode": {
						"type": "string",
						"default": "AH52F7",
                        "description": "Minimum of six characters"
					},
					"discounts": {
						"type": "integer",
						"format": "int32"
					},
					"shipping": {
						"type": "integer",
						"format": "int32"
					},
					"taxes": {
						"type": "integer",
						"format": "int32"
					},
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Item"
						},
						"description": ""
					},
					"itemsTotal": {
						"type": "integer",
						"format": "int32"
					}
				},
				"default": {
					"grandTotal": 182,
					"relationName": null,
					"redemptionCode": "XTYB",
					"discounts": 20,
					"shipping": 2,
					"taxes": 0,
					"items": [
						{
							"productId": "2000000",
							"id": "2000002",
							"refId": "MEV41",
							"name": null,
							"price": 200,
							"quantity": 1
						}
					],
					"itemsTotal": 200
				}
			},
			"Item": {
				"title": "Item",
				"required": [
					"productId",
					"id",
					"refId",
					"name",
					"price",
					"quantity"
				],
				"type": "object",
				"properties": {
					"productId": {
						"type": "string"
					},
					"id": {
						"type": "string"
					},
					"refId": {
						"type": "string"
					},
					"name": {
						"type": "string",
						"nullable": true
					},
					"price": {
						"type": "integer",
						"format": "int32"
					},
					"quantity": {
						"type": "integer",
						"format": "int32"
					}
				},
				"default": {
					"productId": "2000000",
					"id": "2000002",
					"refId": "MEV41",
					"name": null,
					"price": 200,
					"quantity": 1
				}
			},
			"response": {
				"title": "response",
				"required": [
					"id",
					"provider",
					"balance",
					"_self"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"provider": {
						"type": "string"
					},
					"balance": {
						"type": "number"
					},
					"_self": {
						"$ref": "#/components/schemas/Self"
					}
				},
				"example": {
					"id": "3ad63br54-988e-4a14-8b7f-31fc6a5b955c_24",
					"provider": "ProviderName",
					"balance": 5.9,
					"_self": {
						"href": "/gatewayqa/giftcards/3ad63br54-988e-4a14-8b7f-31fc6a5b955c_24"
					}
				}
			},
			"Self": {
				"title": "Self",
				"required": [
					"href"
				],
				"type": "object",
				"properties": {
					"href": {
						"type": "string"
					}
				},
				"example": {
					"href": "/gatewayqa/giftcards/3ad63br54-988e-4a14-8b7f-31fc6a5b955c_24"
				}
			},
			"response1": {
				"title": "response1",
				"required": [
					"id",
					"redemptionToken",
					"redemptionCode",
					"balance",
					"emissionDate",
					"expiringDate",
					"discount",
					"transaction"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"redemptionToken": {
						"type": "string"
					},
					"redemptionCode": {
						"type": "string",
						"default": "AH52F7",
                        "description": "Minimum of six characters"
					},
					"balance": {
						"type": "number"
					},
					"emissionDate": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					},
					"discount": {
						"type": "boolean"
					},
					"transaction": {
						"$ref": "#/components/schemas/Transaction"
					}
				},
				"example": {
					"id": "3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24",
					"redemptionToken": "XTYB-IOBW-WLJE-SEYG",
					"redemptionCode": "XTYB-IOBW-WLJE-SEYG",
					"balance": 5.9,
					"emissionDate": "2018-03-20T09:37:13.797",
					"expiringDate": "2020-03-18T11:42:55.183",
					"discount": false,
					"transaction": {
						"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions"
					}
				}
			},
			"Transaction": {
				"title": "Transaction",
				"required": [
					"href"
				],
				"type": "object",
				"properties": {
					"href": {
						"type": "string"
					}
				},
				"example": {
					"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions"
				}
			},
			"CreateGiftCardRequest": {
				"title": "CreateGiftCardRequest",
				"required": [
					"relationName",
					"caption",
					"profileId"
				],
				"type": "object",
				"properties": {
					"relationName": {
						"type": "string"
					},
					"emissionDate": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					},
					"caption": {
						"type": "string"
					},
					"restrictedToOwner": {
						"type": "boolean"
					},
					"multipleRedemptions": {
						"type": "boolean"
					},
					"multipleCredits": {
						"type": "boolean"
					},
					"profileId": {
						"type": "string"
					}
				},
				"default": {
					"relationName": "rewards-program",
					"emissionDate": "2011-02-04T17:02:19.17",
					"expiringDate": "2020-02-04T17:02:19.17",
					"caption": "rewards program",
					"restrictedToOwner": true,
					"multipleRedemptions": true,
					"multipleCredits": true,
					"profileId": "92de2449"
				}
			},
			"CreateGiftCardTransactionRequest": {
				"title": "CreateGiftCardTransactionRequest",
				"required": [
					"operation",
					"value",
					"description",
					"redemptionToken",
					"redemptionCode",
					"requestId",
					"orderInfo"
				],
				"type": "object",
				"properties": {
					"operation": {
						"type": "string"
					},
					"value": {
						"type": "number"
					},
					"description": {
						"type": "string"
					},
					"redemptionToken": {
						"type": "string"
					},
					"redemptionCode": {
						"type": "string",
						"default": "AH52F7",
                        "description": "Minimum of six characters",
						"nullable": true
					},
					"requestId": {
						"type": "string"
					},
					"orderInfo": {
						"$ref": "#/components/schemas/OrderInfo"
					}
				},
				"default": {
					"operation": "Credit",
					"value": 28,
					"description": "example",
					"redemptionToken": "QFJA",
					"redemptionCode": null,
					"requestId": "v291",
					"orderInfo": {
						"orderId": "v291",
						"sequence": 2915869,
						"cart": {
							"items": [
								{
									"id": "2000330",
									"productId": "2000196",
									"refId": null,
									"name": "Product",
									"value": 15,
									"price": 15,
									"quantity": 1,
									"shippingDiscount": 0,
									"discount": 0,
									"priceTags": []
								}
							],
							"grandTotal": 0,
							"discounts": 0,
							"shipping": 0,
							"taxes": 0,
							"itemsTotal": 15
						},
						"clientProfile": {
							"email": "email@domain.com",
							"firstName": "customer",
							"lastName": "customer",
							"document": "10617764093",
							"documentType": "cpf",
							"phone": "+5521999999999",
							"birthDate": "0001-01-01T00:00:00",
							"isCorporate": false
						},
						"shipping": {
							"receiverName": "name",
							"postalCode": "24417-246",
							"city": "Rio de Janeiro",
							"state": "RJ",
							"country": "BRA",
							"street": "address",
							"number": "9678",
							"neighborhood": "address",
							"complement": "address",
							"reference": "address"
						}
					}
				}
			},
			"OrderInfo": {
				"title": "OrderInfo",
				"required": [
					"orderId",
					"sequence",
					"cart",
					"clientProfile",
					"shipping"
				],
				"type": "object",
				"properties": {
					"orderId": {
						"type": "string"
					},
					"sequence": {
						"type": "integer",
						"format": "int32"
					},
					"cart": {
						"$ref": "#/components/schemas/Cart1"
					},
					"clientProfile": {
						"$ref": "#/components/schemas/ClientProfile"
					},
					"shipping": {
						"$ref": "#/components/schemas/Shipping"
					}
				},
				"default": {
					"orderId": "v2915",
					"sequence": 2915869,
					"cart": {
						"items": [
							{
								"id": "2030",
								"productId": "2196",
								"refId": null,
								"name": "Product",
								"value": 15,
								"price": 15,
								"quantity": 1,
								"shippingDiscount": 0,
								"discount": 0,
								"priceTags": []
							}
						],
						"grandTotal": 0,
						"discounts": 0,
						"shipping": 0,
						"taxes": 0,
						"itemsTotal": 15
					},
					"clientProfile": {
						"email": "email@domain.com",
						"firstName": "customer",
						"lastName": "customer",
						"document": "99999999999",
						"documentType": "cpf",
						"phone": "+5521999999999",
						"birthDate": "0001-01-01T00:00:00",
						"isCorporate": false
					},
					"shipping": {
						"receiverName": "customer",
						"postalCode": "24417-246",
						"city": "Rio de Janeiro",
						"state": "RJ",
						"country": "BRA",
						"street": "address",
						"number": "9678",
						"neighborhood": "address",
						"complement": "address",
						"reference": "address"
					}
				}
			},
			"Cart1": {
				"title": "Cart1",
				"required": [
					"items",
					"grandTotal",
					"discounts",
					"shipping",
					"taxes",
					"itemsTotal"
				],
				"type": "object",
				"properties": {
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Item1"
						},
						"description": ""
					},
					"grandTotal": {
						"type": "integer",
						"format": "int32"
					},
					"discounts": {
						"type": "integer",
						"format": "int32"
					},
					"shipping": {
						"type": "integer",
						"format": "int32"
					},
					"taxes": {
						"type": "integer",
						"format": "int32"
					},
					"itemsTotal": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"items": [
						{
							"id": "2000330",
							"productId": "2000196",
							"refId": null,
							"name": "T-Shirt M",
							"value": 15,
							"price": 15,
							"quantity": 1,
							"shippingDiscount": 0,
							"discount": 0,
							"priceTags": []
						}
					],
					"grandTotal": 0,
					"discounts": 0,
					"shipping": 0,
					"taxes": 0,
					"itemsTotal": 15
				}
			},
			"Item1": {
				"title": "Item1",
				"required": [
					"id",
					"productId",
					"refId",
					"name",
					"value",
					"price",
					"quantity",
					"shippingDiscount",
					"discount",
					"priceTags"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"productId": {
						"type": "string"
					},
					"refId": {
						"type": "string",
						"nullable": true
					},
					"name": {
						"type": "string"
					},
					"value": {
						"type": "integer",
						"format": "int32"
					},
					"price": {
						"type": "integer",
						"format": "int32"
					},
					"quantity": {
						"type": "integer",
						"format": "int32"
					},
					"shippingDiscount": {
						"type": "integer",
						"format": "int32"
					},
					"discount": {
						"type": "integer",
						"format": "int32"
					},
					"priceTags": {
						"type": "array",
						"items": {
							"type": "string"
						},
						"description": ""
					}
				},
				"default": {
					"id": "20330",
					"productId": "20196",
					"refId": null,
					"name": "Product",
					"value": 15,
					"price": 15,
					"quantity": 1,
					"shippingDiscount": 0,
					"discount": 0,
					"priceTags": []
				}
			},
			"ClientProfile": {
				"title": "ClientProfile",
				"required": [
					"email",
					"firstName",
					"lastName",
					"document",
					"documentType",
					"phone",
					"birthDate",
					"isCorporate"
				],
				"type": "object",
				"properties": {
					"email": {
						"type": "string"
					},
					"firstName": {
						"type": "string"
					},
					"lastName": {
						"type": "string"
					},
					"document": {
						"type": "string"
					},
					"documentType": {
						"type": "string"
					},
					"phone": {
						"type": "string"
					},
					"birthDate": {
						"type": "string"
					},
					"isCorporate": {
						"type": "boolean"
					}
				},
				"example": {
					"email": "email@domain.com",
					"firstName": "John",
					"lastName": "Smith",
					"document": "10617764093",
					"documentType": "cpf",
					"phone": "+5521993759875",
					"birthDate": "0001-01-01T00:00:00",
					"isCorporate": false
				}
			},
			"Shipping": {
				"title": "Shipping",
				"required": [
					"receiverName",
					"postalCode",
					"city",
					"state",
					"country",
					"street",
					"number",
					"neighborhood",
					"complement",
					"reference"
				],
				"type": "object",
				"properties": {
					"receiverName": {
						"type": "string"
					},
					"postalCode": {
						"type": "string"
					},
					"city": {
						"type": "string"
					},
					"state": {
						"type": "string"
					},
					"country": {
						"type": "string"
					},
					"street": {
						"type": "string"
					},
					"number": {
						"type": "string"
					},
					"neighborhood": {
						"type": "string"
					},
					"complement": {
						"type": "string"
					},
					"reference": {
						"type": "string"
					}
				},
				"example": {
					"receiverName": "John Smith",
					"postalCode": "24417-246",
					"city": "Leblon",
					"state": "RJ",
					"country": "BRA",
					"street": "Rua Aidea Barreto do Couto",
					"number": "9678",
					"neighborhood": "",
					"complement": "",
					"reference": ""
				}
			},
			"response2": {
				"title": "response2",
				"required": [
					"cardId",
					"id",
					"_self"
				],
				"type": "object",
				"properties": {
					"cardId": {
						"type": "string"
					},
					"id": {
						"type": "string"
					},
					"_self": {
						"$ref": "#/components/schemas/Self"
					}
				},
				"example": {
					"cardId": "24",
					"id": "68347b311ce5407c90fa5316975d047a",
					"_self": {
						"href": "gatewayqa/giftcards/24/transactions/68347b311ce5407c90fa5316975d047a"
					}
				}
			},
			"GetGiftCardTransactionbyID": {
				"title": "GetGiftCardTransactionbyID",
				"required": [
					"value",
					"description",
					"date",
					"requestId",
					"orderInfo",
					"settlement",
					"cancellation",
					"authorization",
					"operation"
				],
				"type": "object",
				"properties": {
					"value": {
						"type": "number"
					},
					"description": {
						"type": "string"
					},
					"date": {
						"type": "string"
					},
					"requestId": {
						"type": "string"
					},
					"orderInfo": {
						"$ref": "#/components/schemas/OrderInfo1"
					},
					"settlement": {
						"$ref": "#/components/schemas/Settlement"
					},
					"cancellation": {
						"$ref": "#/components/schemas/Cancellation"
					},
					"authorization": {
						"$ref": "#/components/schemas/Authorization"
					},
					"operation": {
						"type": "string"
					}
				},
				"example": {
					"value": 5.92,
					"description": "Order v2915869org-02",
					"date": "2019-03-18T14:42:32.1291783Z",
					"requestId": "v2915869org-02",
					"orderInfo": {
						"orderId": "v2915869org-02",
						"sequence": 2915860,
						"cart": {
							"items": [
								{
									"id": "2000330",
									"productId": "2000196",
									"name": "T-Shirt M",
									"price": 15,
									"sellingPrice": 0,
									"quantity": 1,
									"totalShippingDiscount": 0,
									"totalDiscount": 0,
									"priceTags": []
								}
							],
							"grandTotal": 0,
							"discounts": 0,
							"shipping": 0,
							"taxes": 0,
							"itemsTotal": 15
						},
						"clientProfile": {
							"email": "email@domain.com",
							"firstName": "John",
							"lastName": "Smith",
							"document": "10617764093",
							"documentType": "cpf",
							"phone": "+5521993759875",
							"birthDate": "0001-01-01T00:00:00",
							"isCorporate": false
						},
						"shipping": {
							"receiverName": "John Smith",
							"postalCode": "24417-246",
							"city": "Leblon",
							"state": "RJ",
							"country": "BRA",
							"street": "Rua Aidea Barreto do Couto",
							"number": "9678",
							"neighborhood": "",
							"complement": "",
							"reference": ""
						}
					},
					"settlement": {
						"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/settlements"
					},
					"cancellation": {
						"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/cancellations"
					},
					"authorization": {
						"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/authorization"
					},
					"operation": "Debit"
				}
			},
			"OrderInfo1": {
				"title": "OrderInfo1",
				"required": [
					"orderId",
					"sequence",
					"cart",
					"clientProfile",
					"shipping"
				],
				"type": "object",
				"properties": {
					"orderId": {
						"type": "string"
					},
					"sequence": {
						"type": "integer",
						"format": "int32"
					},
					"cart": {
						"$ref": "#/components/schemas/Cart2"
					},
					"clientProfile": {
						"$ref": "#/components/schemas/ClientProfile"
					},
					"shipping": {
						"$ref": "#/components/schemas/Shipping"
					}
				},
				"example": {
					"orderId": "v2915869org-02",
					"sequence": 2915860,
					"cart": {
						"items": [
							{
								"id": "2000330",
								"productId": "2000196",
								"name": "T-Shirt M",
								"price": 15,
								"sellingPrice": 0,
								"quantity": 1,
								"totalShippingDiscount": 0,
								"totalDiscount": 0,
								"priceTags": []
							}
						],
						"grandTotal": 0,
						"discounts": 0,
						"shipping": 0,
						"taxes": 0,
						"itemsTotal": 15
					},
					"clientProfile": {
						"email": "email@domain.com",
						"firstName": "John",
						"lastName": "Smith",
						"document": "10617764093",
						"documentType": "cpf",
						"phone": "+5521993759875",
						"birthDate": "0001-01-01T00:00:00",
						"isCorporate": false
					},
					"shipping": {
						"receiverName": "John Smith",
						"postalCode": "24417-246",
						"city": "Leblon",
						"state": "RJ",
						"country": "BRA",
						"street": "Rua Aidea Barreto do Couto",
						"number": "9678",
						"neighborhood": "",
						"complement": "",
						"reference": ""
					}
				}
			},
			"Cart2": {
				"title": "Cart2",
				"required": [
					"items",
					"grandTotal",
					"discounts",
					"shipping",
					"taxes",
					"itemsTotal"
				],
				"type": "object",
				"properties": {
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Item2"
						},
						"description": ""
					},
					"grandTotal": {
						"type": "integer",
						"format": "int32"
					},
					"discounts": {
						"type": "integer",
						"format": "int32"
					},
					"shipping": {
						"type": "integer",
						"format": "int32"
					},
					"taxes": {
						"type": "integer",
						"format": "int32"
					},
					"itemsTotal": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"items": [
						{
							"id": "2000330",
							"productId": "2000196",
							"name": "T-Shirt M",
							"price": 15,
							"sellingPrice": 0,
							"quantity": 1,
							"totalShippingDiscount": 0,
							"totalDiscount": 0,
							"priceTags": []
						}
					],
					"grandTotal": 0,
					"discounts": 0,
					"shipping": 0,
					"taxes": 0,
					"itemsTotal": 15
				}
			},
			"Item2": {
				"title": "Item2",
				"required": [
					"id",
					"productId",
					"name",
					"price",
					"sellingPrice",
					"quantity",
					"totalShippingDiscount",
					"totalDiscount",
					"priceTags"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"productId": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"price": {
						"type": "integer",
						"format": "int32"
					},
					"sellingPrice": {
						"type": "integer",
						"format": "int32"
					},
					"quantity": {
						"type": "integer",
						"format": "int32"
					},
					"totalShippingDiscount": {
						"type": "integer",
						"format": "int32"
					},
					"totalDiscount": {
						"type": "integer",
						"format": "int32"
					},
					"priceTags": {
						"type": "array",
						"items": {
							"type": "string"
						},
						"description": ""
					}
				},
				"example": {
					"id": "2000330",
					"productId": "2000196",
					"name": "T-Shirt M",
					"price": 15,
					"sellingPrice": 0,
					"quantity": 1,
					"totalShippingDiscount": 0,
					"totalDiscount": 0,
					"priceTags": []
				}
			},
			"Settlement": {
				"title": "Settlement",
				"required": [
					"href"
				],
				"type": "object",
				"properties": {
					"href": {
						"type": "string"
					}
				},
				"example": {
					"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/settlements"
				}
			},
			"Cancellation": {
				"title": "Cancellation",
				"required": [
					"href"
				],
				"type": "object",
				"properties": {
					"href": {
						"type": "string"
					}
				},
				"example": {
					"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/cancellations"
				}
			},
			"Authorization": {
				"title": "Authorization",
				"required": [
					"href"
				],
				"type": "object",
				"properties": {
					"href": {
						"type": "string"
					}
				},
				"example": {
					"href": "/gatewayqa/giftcards/3b1abc17-988e-4a14-8b7f-31fc6a5b955c_24/transactions/e122ebd4501a4b3b93640b7444ac425d/authorization"
				}
			},
			"response4": {
				"title": "response4",
				"required": [
					"oid",
					"value",
					"date"
				],
				"type": "object",
				"properties": {
					"oid": {
						"type": "string"
					},
					"value": {
						"type": "number"
					},
					"date": {
						"type": "string"
					}
				},
				"example": {
					"oid": "e122ebd4501a4b3b93640b7444ac425d",
					"value": 5.92,
					"date": "2019-03-18T14:42:32.1291783Z"
				}
			},
			"CreateGiftCardTransactionCancellationRequest": {
				"title": "CreateGiftCardTransactionCancellationRequest",
				"required": [
					"value",
					"requestId"
				],
				"type": "object",
				"properties": {
					"value": {
						"type": "number",
						"default": 4
					},
					"requestId": {
						"type": "string",
						"default": "12093"
					}
				},
				"example": {
					"value": 4.1,
					"requestId": "12093812masoidj120398"
				}
			},
			"CreateGiftCardTransactionSettlementRequest": {
				"title": "CreateGiftCardTransactionSettlementRequest",
				"required": [
					"value",
					"requestId"
				],
				"type": "object",
				"properties": {
					"value": {
						"type": "number",
						"default": 1.8

					},
					"requestId": {
						"type": "string",
						"default": "1209381"
					}
				},
				"example": {
					"value": 1.8,
					"requestId": "12093812masoidj120398"
				}
			}
		},
		"securitySchemes": {
			"appKey": {
				"type": "apiKey",
				"in": "header",
				"name": "X-VTEX-API-AppKey"
			},
			"appToken": {
				"type": "apiKey",
				"in": "header",
				"name": "X-VTEX-API-AppToken"
			}
		}
	},
	"tags": [
		{
			"name": "Gift Cards"
		},
		{
			"name": "Transactions"
		}
	],
	"security": [
		{
			"appKey": [],
			"appToken": []
		}
	]
}