{
    "openapi": "3.0.0",
    "info": {
        "title": "Subscription (v1 - deprecated)",
        "description": "",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://{accountName}.{environment}.com.br/api",
            "description": "VTEX server url",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL",
                    "default": "{accountName}"
                },
                "environment": {
                    "description": "Environment to use. Used as part of the URL.",
                    "default": "{environment}"
                }
            }
        }
    ],
    "paths": {
        "/subscriptions/{recurrenceId}": {
            "get": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Get Subscription by recurrenceId",
                "description": "Retrieves a given Subscription (formerly recurrence) by recurrenceId.",
                "operationId": "GetRecurrencebyrecurrenceId",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "recurrenceId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            },
            "patch": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Update partial Subscription",
                "description": "Updates partial information of a given subscription (formerly Recurrence).",
                "operationId": "Updatepartialrecurrence",
                "parameters": [
                    {
                        "name": "recurrenceId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdatepartialrecurrenceRequest"
                            },
                            "example": {
                                "deliveryDay": 18,
                                "deliveryWeekday": "Monday",
                                "status": "inactive"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/subscriptions": {
            "get": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Get Subscriptions",
                "description": "Retrieves a given Subscription (formerly recurrence). There are three options of filtering your Subscruptions v1. It's possible to get a list of all Subscriptions v1, by not adding any query params to your request, and simply executing a call to the url. It is also possible to list the Subscriptions by email, filtering by the email query param. And finnally, it is possible to list recurrences with failures on the last execution cycle, filtering by the cycleStatus query param.",
                "operationId": "GetRecurrencebyemail",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "description": "If you wish to list tasks by email, insert the desired user's email.",
                        "required": false,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{{email}}"
                        }
                    },
                    {
                        "name": "cycleStatus",
                        "in": "query",
                        "description": "If you wish to list tasks by Subscriptions with failures on the last execution cycle, insert the desired cycleStatus.",
                        "required": false,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{{cycleStatus}}"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            },
            "put": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Update Subscription",
                "description": "Updates details of a given Subscription (formerly recurrence).",
                "operationId": "Updaterecurrence",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdaterecurrenceRequest"
                            },
                            "example": {
                                "email": "user@vtex.com.br",
                                "deliveryDay": 26,
                                "deliveryWeekday": "Friday",
                                "items": [
                                    {
                                        "sku": "18",
                                        "seller": "1",
                                        "quantity": 2,
                                        "frequency": {
                                            "periodicity": "weekly",
                                            "interval": 1
                                        },
                                        "shippingAddressId": "-1461618656161"
                                    }
                                ],
                                "paymentAccountId": "87FE21B06C0D42908D31A5B11E6FC043"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/subscriptions/{recurrenceId}/items": {
            "post": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Add Subscription item",
                "description": "Adds an item to a Subscription (formerly Recurrence).",
                "operationId": "Addrecurrenceitem",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "recurrenceId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/AddrecurrenceitemRequest"
                                },
                                "description": ""
                            },
                            "example": [
                                {
                                    "sku": "20",
                                    "seller": "1",
                                    "quantity": 2,
                                    "frequency": {
                                        "periodicity": "monthly",
                                        "interval": 1
                                    },
                                    "shippingAddressId": "-1461618656161"
                                }
                            ]
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/subscriptions/{recurrenceId}/reindex": {
            "patch": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Reindex Subscription",
                "description": "Alters the frequency of a given Subscription (formerly Recurrence) by changing period and interval.",
                "operationId": "Reindexrecurrence",
                "parameters": [
                    {
                        "name": "recurrenceId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/ReindexrecurrenceRequest"
                                },
                                "description": ""
                            },
                            "example": [
                                {
                                    "frequency": {
                                        "periodicity": "yearly",
                                        "interval": 1
                                    }
                                }
                            ]
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/subscriptions/{recurrenceId}/addresses": {
            "get": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Get Subscription addresses",
                "description": "Retrieves the addresses attached to a given subscription (formerly recurrence) by recurrenceId.",
                "operationId": "Getrecurrenceaddresses",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "recurrenceId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/subscriptions/{recurrenceid}/accounts": {
            "get": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Get payment accounts",
                "description": "Lists payment accounts of a given Subscription (formerly Recurrence) by recurrenceId.",
                "operationId": "Getpaymentaccounts",
                "parameters": [
                    {
                        "name": "recurrenceid",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/subscriptions/settings": {
            "get": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Get Subscription settings",
                "description": "Retrieves your store's Subscriptions' (formerly recurrence) settings.",
                "operationId": "Getrecurrencesettings",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            },
            "put": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Update Subscription settings",
                "description": "Updates the Subscriptions' (formerly Recurrence) settings of your store by salesChannel and defaultSLA.",
                "operationId": "Updaterecurrencesettings",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdaterecurrencesettingsRequest"
                            },
                            "example": {
                                "salesChannel": "1",
                                "defaultSLA": "Normal"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/subscriptions/me": {
            "get": {
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Get self Subscription",
                "description": "Lists details of your self Subscription (formerly Recurrence).",
                "operationId": "Getselfrecurrence",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        }
    },
    "components": {
        "schemas": {
            "AddrecurrenceitemRequest": {
                "title": "AddrecurrenceitemRequest",
                "required": [
                    "sku",
                    "seller",
                    "quantity",
                    "frequency",
                    "shippingAddressId"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string"
                    },
                    "seller": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "frequency": {
                        "$ref": "#/components/schemas/Frequency"
                    },
                    "shippingAddressId": {
                        "type": "string"
                    }
                },
                "example": {
                    "sku": "20",
                    "seller": "1",
                    "quantity": 2,
                    "frequency": {
                        "periodicity": "monthly",
                        "interval": 1
                    },
                    "shippingAddressId": "-1461618656161"
                }
            },
            "Frequency": {
                "title": "Frequency",
                "required": [
                    "periodicity",
                    "interval"
                ],
                "type": "object",
                "properties": {
                    "periodicity": {
                        "type": "string"
                    },
                    "interval": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "example": {
                    "periodicity": "monthly",
                    "interval": 1
                }
            },
            "UpdaterecurrenceRequest": {
                "title": "UpdaterecurrenceRequest",
                "required": [
                    "email",
                    "deliveryDay",
                    "deliveryWeekday",
                    "items",
                    "paymentAccountId"
                ],
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "deliveryDay": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "deliveryWeekday": {
                        "type": "string"
                    },
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Item"
                        },
                        "description": ""
                    },
                    "paymentAccountId": {
                        "type": "string"
                    }
                },
                "example": {
                    "email": "user@vtex.com.br",
                    "deliveryDay": 26,
                    "deliveryWeekday": "Friday",
                    "items": [
                        {
                            "sku": "18",
                            "seller": "1",
                            "quantity": 2,
                            "frequency": {
                                "periodicity": "weekly",
                                "interval": 1
                            },
                            "shippingAddressId": "-1461618656161"
                        }
                    ],
                    "paymentAccountId": "87FE21B06C0D42908D31A5B11E6FC043"
                }
            },
            "Item": {
                "title": "Item",
                "required": [
                    "sku",
                    "seller",
                    "quantity",
                    "frequency",
                    "shippingAddressId"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string"
                    },
                    "seller": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "frequency": {
                        "$ref": "#/components/schemas/Frequency"
                    },
                    "shippingAddressId": {
                        "type": "string"
                    }
                },
                "example": {
                    "sku": "18",
                    "seller": "1",
                    "quantity": 2,
                    "frequency": {
                        "periodicity": "weekly",
                        "interval": 1
                    },
                    "shippingAddressId": "-1461618656161"
                }
            },
            "UpdatepartialrecurrenceRequest": {
                "title": "UpdatepartialrecurrenceRequest",
                "required": [
                    "deliveryDay",
                    "deliveryWeekday",
                    "status"
                ],
                "type": "object",
                "properties": {
                    "deliveryDay": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "deliveryWeekday": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    }
                },
                "example": {
                    "deliveryDay": 18,
                    "deliveryWeekday": "Monday",
                    "status": "inactive"
                }
            },
            "ReindexrecurrenceRequest": {
                "title": "ReindexrecurrenceRequest",
                "required": [
                    "frequency"
                ],
                "type": "object",
                "properties": {
                    "frequency": {
                        "$ref": "#/components/schemas/Frequency"
                    }
                },
                "example": {
                    "frequency": {
                        "periodicity": "yearly",
                        "interval": 1
                    }
                }
            },
            "UpdaterecurrencesettingsRequest": {
                "title": "UpdaterecurrencesettingsRequest",
                "required": [
                    "salesChannel",
                    "defaultSLA"
                ],
                "type": "object",
                "properties": {
                    "salesChannel": {
                        "type": "string"
                    },
                    "defaultSLA": {
                        "type": "string"
                    }
                },
                "example": {
                    "salesChannel": "1",
                    "defaultSLA": "Normal"
                }
            }
        },
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey"
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken"
            }
        }
    },
    "tags": [
        {
            "name": "Miscellaneous",
            "description": ""
        }
    ],
    "security": [
        {
            "appKey": [],
            "appToken": []
        }
    ]
}